# Auto-generated by launcher.py — will be overwritten
WR_PLUS_PATH = '/Volumes/Petersen-Lab/z_LSENS/Share/Loris_Fabbro/AO/NWB_files/WR+'
WR_MINUS_PATH = '/Volumes/Petersen-Lab/z_LSENS/Share/Loris_Fabbro/AO/NWB_files/WR-'
MATCHED_FILES_WR_PLUS = ['/Volumes/Petersen-Lab/z_LSENS/Share/Loris_Fabbro/AO/NWB_files/WR+/AO039_20190627_151857.nwb', '/Volumes/Petersen-Lab/z_LSENS/Share/Loris_Fabbro/AO/NWB_files/WR+/AO039_20190626_160524.nwb']
MATCHED_FILES_WR_MINUS = ['/Volumes/Petersen-Lab/z_LSENS/Share/Loris_Fabbro/AO/NWB_files/WR-/AO081_20210505_192239.nwb', '/Volumes/Petersen-Lab/z_LSENS/Share/Loris_Fabbro/AO/NWB_files/WR-/AO081_20210507_131703.nwb', '/Volumes/Petersen-Lab/z_LSENS/Share/Loris_Fabbro/AO/NWB_files/WR-/AO081_20210506_132701.nwb']
